10fives-numpy.py

In [ ]:
import numpy as np
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]

10zeros-numpy.py

In [ ]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

1split-basic.py

In [ ]:
string = "Hi there Sam!"
print(string.split())

['Hi', 'there', 'Sam!']

2col3row-panda.py

In [4]:
import pandas as pd
data = [['tom', 10], ['nick', 15], ['juli', 14]]
df = pd.DataFrame(data, columns=['Name', 'Age'])
print(df)

   Name  Age
0   tom   10
1  nick   15
2  juli   14

2d-panda.py

In [2]:
import pandas as pd  
      
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]] 
      
df = pd.DataFrame(lists, columns =['ID', 'Name', 'Age']) 
print(df)

   ID Name  Age
0   1  aaa   22
1   2  bbb   25
2   3  ccc   24

3d-numpy.py

In [5]:
import numpy as np
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

Basic Python
1. Split this string

In [6]:
s = "Hi there Sam!"

2. Use .format() to print the following string.
Output should be: The diameter of Earth is 12742 kilometers.

In [7]:
planet = "Earth"
diameter = 12742

3. In this nest dictionary grab the word "hello"

In [8]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

Numpy

In [9]:
import numpy as np

4.1 Create an array of 10 zeros?
4.2 Create an array of 10 fives?

5. Create an array of all the even integers from 20 to 35

6. Create a 3x3 matrix with values ranging from 0 to 8

7. Concatenate a and b
a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

Pandas
8. Create a dataframe with 3 rows and 2 columns

In [10]:
import pandas as pd

9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

10. Create 2D list to DataFrame

In [12]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

concat-numpy.py

In [13]:
import numpy as np
a = np.array([1, 2, 3])
print(a)
b = np.array([4, 5, 6])
print(b)
print('\n---Result of a and b---')
print(np.concatenate((a, b)))

[1 2 3]
[4 5 6]

---Result of a and b---
[1 2 3 4 5 6]

date-pandas.py

In [14]:
import datetime
import pandas as pd
 
# initializing date
test_date = datetime.datetime.strptime("01-01-2023", "%d-%m-%Y")
 
# initializing periods
periods = datetime.datetime.strptime("02-02-2023", "%d-%m-%Y")
 
date_generated = pd.date_range(test_date, periods)
print(date_generated.strftime("%d-%m-%Y"))

Index(['01-01-2023', '02-01-2023', '03-01-2023', '04-01-2023', '05-01-2023',
       '06-01-2023', '07-01-2023', '08-01-2023', '09-01-2023', '10-01-2023',
       '11-01-2023', '12-01-2023', '13-01-2023', '14-01-2023', '15-01-2023',
       '16-01-2023', '17-01-2023', '18-01-2023', '19-01-2023', '20-01-2023',
       '21-01-2023', '22-01-2023', '23-01-2023', '24-01-2023', '25-01-2023',
       '26-01-2023', '27-01-2023', '28-01-2023', '29-01-2023', '30-01-2023',
       '31-01-2023', '01-02-2023', '02-02-2023'],
      dtype='object')

earth-basic.py

In [15]:
planet = "Earth"
diameter = 12742
print( 'The diameter of {} is {} kilometers.' .format(planet,diameter));

The diameter of Earth is 12742 kilometers.

even-numpy.py

In [16]:
import numpy as np
array=np.arange(20,36,2)
print("Array of all the even integers from 20 to 36")
print(array)

Array of all the even integers from 20 to 36
[20 22 24 26 28 30 32 34]

hello-basic.py

In [17]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

hello